Issue/6
DD2480-2021-group-22/dd2480-lab-2 pull request #12
Opened 2021-02-04 20:54 UTC by grundb

Implements repo cloning and appropriate tests.

2021-02-04 23:29 UTC, grundb reviewed
keep in mind these things can be changed, and please do provide feedback

2021-02-07 12:16 UTC, kittytinythai requested changes

2021-02-07 12:16 UTC, kittytinythai commented on src/main/java/RepoSnapshot.java
> +         /* ProcessBuilder pb = new ProcessBuilder();
Remove commented code

2021-02-07 12:17 UTC, kittytinythai approved these changes
LGTM

2021-02-07 12:18 UTC, merged